/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/upload': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Upload */
    post: operations['upload_api_upload_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/jobs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Jobs */
    get: operations['list_jobs_api_jobs_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/jobs/{job_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Status */
    get: operations['get_status_api_jobs__job_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/jobs/{job_id}/segments': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Update Segments */
    put: operations['update_segments_api_jobs__job_id__segments_put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/jobs/{job_id}/frames': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Frames */
    get: operations['list_frames_api_jobs__job_id__frames_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/jobs/{job_id}/frames/{name}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Frame */
    get: operations['get_frame_api_jobs__job_id__frames__name__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/jobs/{job_id}/source': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Source */
    get: operations['get_source_api_jobs__job_id__source_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/jobs/{job_id}/render': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Render */
    get: operations['get_render_api_jobs__job_id__render_get']
    put?: never
    /** Start Render */
    post: operations['start_render_api_jobs__job_id__render_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/jobs/{job_id}/events': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Legacy Job Events */
    get: operations['legacy_job_events_api_jobs__job_id__events_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/projects': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Projects */
    get: operations['list_projects_api_v1_projects_get']
    put?: never
    /** Create Project */
    post: operations['create_project_api_v1_projects_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/projects/{project_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Project */
    get: operations['get_project_api_v1_projects__project_id__get']
    put?: never
    post?: never
    /**
     * Delete Project
     * @description Delete the project, its rows (FK cascade), and all artifact files.
     */
    delete: operations['delete_project_api_v1_projects__project_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/projects/{project_id}/assets': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Upload Asset */
    post: operations['upload_asset_api_v1_projects__project_id__assets_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/assets/{asset_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Asset */
    get: operations['get_asset_api_v1_assets__asset_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/assets/{asset_id}/frames': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Frames */
    get: operations['list_frames_api_v1_assets__asset_id__frames_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/assets/{asset_id}/frames/{name}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Frame */
    get: operations['get_frame_api_v1_assets__asset_id__frames__name__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/assets/{asset_id}/source': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Source */
    get: operations['get_source_api_v1_assets__asset_id__source_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/assets/{asset_id}/render': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Render */
    get: operations['get_render_api_v1_assets__asset_id__render_get']
    put?: never
    /** Start Render */
    post: operations['start_render_api_v1_assets__asset_id__render_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/projects/{project_id}/timeline': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Timeline */
    get: operations['get_timeline_api_v1_projects__project_id__timeline_get']
    /** Update Timeline */
    put: operations['update_timeline_api_v1_projects__project_id__timeline_put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/projects/{project_id}/timeline/versions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Timeline Versions */
    get: operations['list_timeline_versions_api_v1_projects__project_id__timeline_versions_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/projects/{project_id}/timeline/versions/{version}/restore': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Restore Timeline Version */
    post: operations['restore_timeline_version_api_v1_projects__project_id__timeline_versions__version__restore_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/assets/{asset_id}/events': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Asset Events */
    get: operations['asset_events_api_v1_assets__asset_id__events_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Health
     * @description Liveness probe (used by the Docker HEALTHCHECK and uptime monitors).
     */
    get: operations['health_api_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Index */
    get: operations['index__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * Asset
     * @description An ingested source file plus its analysis.
     *
     *     Lives in a project; the pre-Plan-1 'job' became exactly this (ids were
     *     preserved by the cutover migration, so legacy /api/jobs/{id} URLs work).
     */
    Asset: {
      /** Id */
      id: string
      /** Project Id */
      project_id: string
      /** Filename */
      filename: string
      /**
       * Status
       * @enum {string}
       */
      status: 'uploaded' | 'sampling' | 'analyzing' | 'ready' | 'rendering' | 'rendered' | 'failed'
      /** Error */
      error?: string | null
      meta?: components['schemas']['VideoMeta'] | null
      /**
       * Segments
       * @default []
       */
      segments: components['schemas']['Segment'][]
      /**
       * Has Render
       * @default false
       */
      has_render: boolean
      /** Created At */
      created_at?: string | null
      /** Progress */
      progress?: string | null
      /**
       * Frame Notes
       * @default []
       */
      frame_notes: components['schemas']['FrameNote'][]
      /**
       * Transcript
       * @default []
       */
      transcript: components['schemas']['TranscriptLine'][]
    }
    /** Body_upload_api_upload_post */
    Body_upload_api_upload_post: {
      /** Video */
      video: string
    }
    /** Body_upload_asset_api_v1_projects__project_id__assets_post */
    Body_upload_asset_api_v1_projects__project_id__assets_post: {
      /** Video */
      video: string
    }
    /** Clip */
    Clip: {
      /** Id */
      id?: string
      /**
       * Name
       * @default
       */
      name: string
      source: components['schemas']['ClipSource']
      /**
       * Record Start S
       * @default 0
       */
      record_start_s: number
      /**
       * Reason
       * @default
       */
      reason: string
      /**
       * Confidence
       * @default 1
       */
      confidence: number
      /**
       * Enabled
       * @default true
       */
      enabled: boolean
    }
    /**
     * ClipSource
     * @description Which part of which asset the clip plays.
     */
    ClipSource: {
      /** Asset Id */
      asset_id: string
      /** In S */
      in_s: number
      /** Out S */
      out_s: number
    }
    /** CreateProjectRequest */
    CreateProjectRequest: {
      /** Name */
      name: string
    }
    /** FrameNote */
    FrameNote: {
      /** Timestamp S */
      timestamp_s: number
      /**
       * Description
       * @default
       */
      description: string
      /**
       * Label
       * @default other
       * @enum {string}
       */
      label: 'core' | 'filler' | 'dead_air' | 'intro_outro' | 'repetition' | 'other'
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** Project */
    Project: {
      /** Id */
      id: string
      /** Name */
      name: string
      /** User Id */
      user_id?: string | null
      /** Created At */
      created_at?: string | null
    }
    /** ProjectDetail */
    ProjectDetail: {
      project: components['schemas']['Project']
      /** Assets */
      assets: components['schemas']['Asset'][]
      timeline?: components['schemas']['TimelineInfo'] | null
    }
    /** ProjectSummary */
    ProjectSummary: {
      /** Id */
      id: string
      /** Name */
      name: string
      /** Created At */
      created_at?: string | null
      /**
       * Assets
       * @default 0
       */
      assets: number
      /** Duration S */
      duration_s?: number | null
      /** Timeline Id */
      timeline_id?: string | null
    }
    /**
     * Segment
     * @description A keep-range in the edit decision list.
     */
    Segment: {
      /** Start S */
      start_s: number
      /** End S */
      end_s: number
      /**
       * Reason
       * @default
       */
      reason: string
      /**
       * Confidence
       * @default 1
       */
      confidence: number
    }
    /** Timeline */
    Timeline: {
      /**
       * Schema Version
       * @default 1
       */
      schema_version: number
      /**
       * Name
       * @default main
       */
      name: string
      /** Frame Rate */
      frame_rate?: number | null
      /**
       * Tracks
       * @default []
       */
      tracks: components['schemas']['Track'][]
    }
    /**
     * TimelineInfo
     * @description API envelope: a stored timeline with identity and version.
     */
    TimelineInfo: {
      /** Id */
      id: string
      /** Project Id */
      project_id: string
      /** Name */
      name: string
      /** Version */
      version: number
      document: components['schemas']['Timeline']
      /** Updated At */
      updated_at?: string | null
    }
    /** Track */
    Track: {
      /** Id */
      id?: string
      /**
       * Kind
       * @default video
       * @enum {string}
       */
      kind: 'video' | 'audio'
      /** Name */
      name: string
      /**
       * Clips
       * @default []
       */
      clips: components['schemas']['Clip'][]
    }
    /** TranscriptLine */
    TranscriptLine: {
      /** Start S */
      start_s: number
      /** End S */
      end_s: number
      /** Text */
      text: string
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
    /** VideoMeta */
    VideoMeta: {
      /**
       * Duration S
       * @default 0
       */
      duration_s: number
      /**
       * Fps
       * @default 0
       */
      fps: number
      /**
       * Width
       * @default 0
       */
      width: number
      /**
       * Height
       * @default 0
       */
      height: number
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  upload_api_upload_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_upload_api_upload_post']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: string
          }
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_jobs_api_jobs_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: unknown
          }[]
        }
      }
    }
  }
  get_status_api_jobs__job_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        job_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Asset']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_segments_api_jobs__job_id__segments_put: {
    parameters: {
      query?: never
      header?: never
      path: {
        job_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['Segment'][]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Asset']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_frames_api_jobs__job_id__frames_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        job_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: unknown
          }[]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_frame_api_jobs__job_id__frames__name__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        job_id: string
        name: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_source_api_jobs__job_id__source_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        job_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_render_api_jobs__job_id__render_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        job_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  start_render_api_jobs__job_id__render_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        job_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: string
          }
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  legacy_job_events_api_jobs__job_id__events_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        job_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_projects_api_v1_projects_get: {
    parameters: {
      query?: {
        limit?: number
        offset?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProjectSummary'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_project_api_v1_projects_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateProjectRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Project']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_project_api_v1_projects__project_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        project_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProjectDetail']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_project_api_v1_projects__project_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        project_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: boolean
          }
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  upload_asset_api_v1_projects__project_id__assets_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        project_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_upload_asset_api_v1_projects__project_id__assets_post']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Asset']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_asset_api_v1_assets__asset_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        asset_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Asset']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_frames_api_v1_assets__asset_id__frames_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        asset_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: unknown
          }[]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_frame_api_v1_assets__asset_id__frames__name__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        asset_id: string
        name: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_source_api_v1_assets__asset_id__source_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        asset_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_render_api_v1_assets__asset_id__render_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        asset_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  start_render_api_v1_assets__asset_id__render_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        asset_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: string
          }
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_timeline_api_v1_projects__project_id__timeline_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        project_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TimelineInfo']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_timeline_api_v1_projects__project_id__timeline_put: {
    parameters: {
      query?: never
      header?: never
      path: {
        project_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['Timeline']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TimelineInfo']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_timeline_versions_api_v1_projects__project_id__timeline_versions_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        project_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: unknown
          }[]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  restore_timeline_version_api_v1_projects__project_id__timeline_versions__version__restore_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        project_id: string
        version: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TimelineInfo']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  asset_events_api_v1_assets__asset_id__events_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        asset_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  health_api_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: string
          }
        }
      }
    }
  }
  index__get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
}
